#!/bin/bash
# Inicia CAVA y lo conecta al visualizador AGS.
# Usado por subprocess() en el widget Right.tsx de AGS.
exec cava -p "$HOME/.config/cava/ags.ini" | "$HOME/.local/bin/ags-cavars" --ags --led
